const h1 = document.querySelector("h1");
h1.style.color = "gold";
h1.style.border = "solid";
h1.style.boxShadow = " 5px 10px #888888";
h1.style.backgroundColor = "teal";
h1.style.display = "flex";
h1.style.boxSizing = "border-box";
h1.style.justifyContent = "center";
h1.style.alignItems = "center";
